import type { Metadata } from "next";

import localFont from "next/font/local";

import { Kanit } from "next/font/google";
import { Navbar } from "@/components/ui/nav-bar";

// const inter = Inter({ subsets: ["latin"] });

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="grid grid-rows-[auto_1fr] min-h-screen">
      <Navbar />
      <main className="h-full ">{children}</main>
    </main>
  );
}
